"""Add marker column to Feedback

Revision ID: d0373cf44a4c
Revises: da4ef1b5487e
Create Date: 2025-01-23 16:55:16.178753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0373cf44a4c'
down_revision = 'da4ef1b5487e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marker', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_column('marker')

    # ### end Alembic commands ###
