"""Initial Migration

Revision ID: da4ef1b5487e
Revises: 
Create Date: 2025-01-20 15:27:05.366302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da4ef1b5487e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.String(length=100), nullable=False),
    sa.Column('pregunta', sa.Text(), nullable=False),
    sa.Column('respuesta', sa.Text(), nullable=False),
    sa.Column('evaluacion', sa.String(length=10), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
